### ISSUE TITLE
[feature request] Renaming and removing categories

### ISSUE THREAD

**Issue by Panja0** [NickSC/nzbFox#10]
The new category feature is awesome! It works great.
Though it would be nice if we could rename the categories ourselves and even remove unused ones.

For instance I have multiple categories for movies in NZBget.
* Films
* Films kids
* Films mother in law (LOL, yeah I know.... )

At the moment there is only one entry for movies. Of course I can link games to Films kids etc
But it would be nice if we can just rename them.

Deleting unused categories would be nice as well.
I don't need reading or games category so I would like to remove them so I have a smaller category list.

Keep up the good work Nick, appreciated!
Just made a small contribution through PayPal. :)
Transaction reference: 5HU44357L0465151G

**Comment by NickSC** [comment]
Thanks for the donation :)

I think I can add a method for removing unused categories. I will make it so if the option is empty, it will not appear in the download prompt category list (e.g. if you set the "TV" category to blank in Options, it won't appear)

As for custom categories, I can probably add a field similar to the personal newznab indexers option, where you can enter `Films (kids),Films (mother in law),Comic Books,Documentaries` and have those appear in the download prompt category list. They must match the full category name in SAB though. So if it is called "FilmsKIDS" in Sab, that is what must be entered in the options of nzbFox, rather than something prettier like "Films (Kids)"

So yeah I believe those features can be added, I shall attempt to have them added by the next update (no ETA though). Thanks for the ideas :)

**Comment by Panja0** [comment]
Sounds good to me! I do use NZBget though. :dancers: 
But for NZBget it probably needs to match the exact/full category as well, which makes sense.

**Comment by NickSC** [comment]
Yeah it's the same deal with NZBGet.

Both requested features have been implemented in nzbFox 1.4.1.
