### ISSUE TITLE
Send to NZBGet doesn't work as expected

### ISSUE THREAD

**Issue by Aimhere2k** [NickSC/nzbFox#23]
nzbFox 1.4.5 running on Firefox 50.1.0, under Windows 10 Home. Used in combination with NZBGet 16.4 on the same PC.

I thought nzbFox was supposed to be able to send NZBs directly to NZBGet, bypassing the need to save the NZB to a disk location. So, when I click on an NZB link in Firefox, I am given the options "Open With", "Save file" (built into Firefox), and "Send to NZBGet" (as added by NZBFox). When I select "Send to NZBGet", with or without specifying a category, I expect it to simply send the NZB to NZBGet with no further user input. 

HOWEVER, what happens instead is, I get a Firefox "Save as" dialog. If I merely cancel this dialog, nothing happens (the NZB does not show up in NZBGet's download queue). But if DO save the NZB file (to any location), then it does appear in NZBGet. In fact, if I deliberately save it to the folder NZBGet is monitoring for NZBs, it will actually appear TWICE in NZBGet's queue (one due to nzbFox, the other due to NZBGet's monitoring).

If nzbFox's "Send to NZBGet" feature is going to insist on a "Save as" dialog, then it's no better than the "Save as" functionality already built into Firefox.

**Comment by NickSC** [comment]
What you've described is a symptom of setting your Firefox to "Always ask me where to save files" instead of the default option of always saving to the Downloads folder/other location. If you want to bypass this window, in "Tools > Options > General", under the "Downloads" header, select "Save files to:"

The "Send to NZBGet" option works by directly uploading the **nzb file** to NZBGet. This requires you to download the nzb file, then it is automatically uploaded to NZBGet and deleted from your download location. If you want it to be completely seamless with no user input, you must use the inline download button on a supported indexer.

**Comment by Aimhere2k** [comment]
But I generally prefer Firefox to always ask me where files should be saved. It fits my workflow better than always saving everything to a single download folder. Is there no way to have an exception just for NZB files?
